back_web/urls.py
from django.conf.urls import url

from back_web import views

urlpatterns = [
    # 登陆
    url(r'^$', views.login, name='login'),
    url(r'^login/', views.login),
    # 注销
    url(r'^logout/', views.logout, name='logout'),

    # 首页 即商品列表
    url(r'^index/', views.index, name='index'),
    # 添加商品
    url(r'^add_goods/', views.add_goods, name='add_goods'),
    # 编辑商品
    url(r'^edit_good/', views.edit_good, name='edit_good'),
    # 删除商品
    url(r'^del_good/', views.del_good, name='del_good'),

    # 添加分组
    url(r'^add_group/', views.add_group, name='add_group'),
    # 显示分组信息
    url(r'^show_group/', views.show_group, name='show_group'),
    # 删除分组
    url(r'^del_group/',views.del_group, name='del_group'),
    # 编辑分组信息
    url(r'^edit_group/', views.edit_group, name='edit_group'),

    # 添加静态文件
    url(r'^add_static/', views.add_static, name='add_static'),
    # 显示静态文件
    url(r'^show_static/', views.show_static, name='show_static'),
    # 编辑静态文件
    url(r'^edit_static/', views.edit_static, name='edit_static'),
    # 删除静态文件
    url(r'^del_static/',views.del_static, name='del_static'),

    # 添加轮播文件
    url(r'^add_banner/', views.add_banner, name='add_banner'),
    # 显示轮播文件
    url(r'^show_banner/', views.show_banner, name='show_banner'),
    # 编辑轮播文件
    url(r'^edit_banner/', views.edit_banner, name='edit_banner'),
    # 删除轮播文件
    url(r'^del_banner/', views.del_banner, name='del_banner'),

    # 添加运费
    url(r'^add_freight/', views.add_freight, name='add_freight'),
    # 显示运费设置
    url(r'^show_freight/', views.show_freight, name='show_freight'),

    # 后台订单显示
    url(r'^show_order/', views.show_order, name='show_order'),
    # 订单状态修改
    url(r'^edit_order/', views.edit_order, name='edit_order'),

    # 显示配送方式
    url(r'^show_distrib/', views.show_distrib, name='show_distrib'),
    # 添加配送方式
    url(r'^add_distrib/', views.add_distrib, name='add_distrib'),
    # 删除url
    url(r'^del_distrib/', views.del_distrib, name='del_distrib'),

]

fruits_family/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fruits_family import settings
from fruits_shop.views import FruitShopView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^back_web/', include('back_web.urls', namespace='back_web')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^fruits_shop/', include('fruits_shop.urls', namespace='fruits_shop')),
    url(r'^$', FruitShopView.as_view()),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^show_address/', views.show_address, name='show_address'),
    url(r'^add_address/', views.add_address, name='add_address'),
    url(r'^edit_address/', views.edit_address, name='edit_address'),
    url(r'^del_address/', views.del_address, name='del_address'),
    url(r'^user_order_info/',views.user_order_info, name='user_order_info'),


]

back_web/views/auth_views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# 登陆
def login(request):

    if request.method == 'GET':
        return render(request, 'back_web/login.html')
    if request.method == 'POST':
        name = request.POST.get('user')
        pwd = request.POST.get('pwd')
        user = auth.authenticate(username=name, password=pwd)
        if user:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('back_web:index'))
        return render(request, 'back_web/login.html',
                      {'msg': '用户名密码错误'})


# 注销
def logout(request):
    if request.method == 'GET':
        auth.logout(request)
        return HttpResponseRedirect(reverse('back_web:login'))

back_web/views/banner_views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


from back_web.models import BannerModel


# 删除轮播文件
def del_banner(request):
    if request.method == 'GET':
        banner_id = request.GET.get('banner_id')
        banner = BannerModel.objects.filter(pk=banner_id).first()
        if banner:
            banner.delete()
        return HttpResponseRedirect(reverse('back_web:show_banner'))


# 编辑轮播文件
def edit_banner(request):
    if request.method == 'GET':
        banner_id = request.GET.get('banner_id')
        banner = BannerModel.objects.filter(pk=banner_id).first()
        if banner:
            return render(request, 'back_web/add_banner.html',
                          {'banner': banner, 'msg': '不改可不填'})
    if request.method == 'POST':
        banner_id = request.GET.get('banner_id')
        banner = BannerModel.objects.filter(pk=banner_id).first()
        if banner:
            name, img = request.POST.get('name'), request.FILES.get('img', '')
            banner.edit(name=name, img=img)
            banner.save()
        return HttpResponseRedirect(reverse('back_web:show_static'))


# 显示轮播图
def show_banner(request):
    if request.method == 'GET':
        banners = BannerModel.objects.all()
        page = int(request.GET.get('page', 1))
        paginator = Paginator(banners, 5)
        banner_list = paginator.page(page)
        data = {
            'banner_list': banner_list,
            'page': page,
            'num': len(banner_list),
        }
        return render(request, 'back_web/show_banner.html', data)


# 添加轮播图
def add_banner(request):
    if request.method == 'GET':
        return render(request, 'back_web/add_banner.html')

    if request.method == 'POST':
        name, img = request.POST.get('name'), request.FILES.get('img')
        banner = BannerModel.objects.filter(name=name).first()
        if banner:
            return render(request, 'back_web/add_banner.html', {'msg': '名称已存在'})
        BannerModel.objects.create(name=name, img=img)
        return HttpResponseRedirect(reverse('back_web:show_banner'))

back_web/views/distrib_views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from back_web.models import DistribModel


# 删除配送方式
def del_distrib(request):
    if request.method == 'GET':
        distrib_id = request.GET.get('distrib_id')
        distrib = DistribModel.objects.filter(pk=distrib_id)
        if distrib:
            distrib.delete()


# 添加配送方式
def add_distrib(request):
    if request.method == 'GET':
        return render(request, 'back_web/add_distrib.html')
    if request.method == 'POST':
        name = request.POST.get('name')
        img = request.FILES.get('img')
        DistribModel.objects.create(name=name, img=img)
        msg = {'msg': '添加成功'}
        return render(request, 'back_web/add_distrib.html', msg)


# 显示配送方式
def show_distrib(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        distribs = DistribModel.objects.all()
        paginator = Paginator(distribs, 5)
        distrib_list = paginator.page(page)
        data = {
            'distrib_list': distrib_list,
            'page': page,
            'num': len(distrib_list),
        }
        return render(request, 'back_web/show_distrib.html', data)

back_web/views/freight_views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from back_web.models import FreightModel


# 显示运费设置信息
def show_freight(request):
    if request.method == 'GET':
        freights = FreightModel.objects.all()
        page = int(request.GET.get('page', 1))
        paginator = Paginator(freights, 5)
        freight_list = paginator.page(page)
        data = {
            'freight_list': freight_list,
            'page': page,
            'num': len(freight_list),
        }
        return render(request, 'back_web/show_freight.html', data)
    raise Http404


# 添加运费设置
def add_freight(request):
    if request.method == 'GET':
        return render(request, 'back_web/add_freight.html')

    if request.method == 'POST':
        address = request.POST.get('address')
        freight = request.POST.get('freight')
        if not all([address, freight]):
            msg = {'msg': '请填写完整信息'}
        if FreightModel.objects.filter(area=address).exists():
            msg = {'msg': '区域地质重复'}
        else:
            FreightModel.objects.create(area=address, cost=freight)
            msg = {'msg': '添加成功'}
        return render(request, 'back_web/add_freight.html', msg)

back_web/views/goods_views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from back_web.models import GoodsModel, GroupModel


# 显示商品&首页
def index(request):
    if request.method == 'GET':
        goods = GoodsModel.objects.all()
        page = int(request.GET.get('page', 1))
        paginator = Paginator(goods, 5)
        good_list = paginator.page(page)
        data = {
            'good_list': good_list,
            'page': page,
            'num': len(goods),
        }
        return render(request, 'back_web/index.html', data)


# 编辑商品
def edit_good(request):
    if request.method == 'GET':
        good_id = request.GET.get('good_id')
        good = GoodsModel.objects.filter(pk=good_id).first()
        if good:
            group_list = GroupModel.objects.all()
            return render(request, 'back_web/add_goods.html',
                          {'group_list': group_list, 'good': good,
                           'msg': '不改可不填'})
    if request.method == 'POST':
        good_id = request.GET.get('good_id')
        good = GoodsModel.objects.filter(pk=good_id).first()
        if good:
            name, description = request.POST.get('name'), request.POST.get('description')
            img, price = request.FILES.get('img', ''), request.POST.get('price')
            intro, format = request.POST.get('intro'), request.POST.get('format')
            group_id = request.POST.get('group')
            group = GroupModel.objects.filter(pk=group_id).first()
            good.edit(name=name, img=img, group=group, price=price,
                      description=description, intro=intro, format=format)
            good.save()
            return HttpResponseRedirect(reverse('back_web:index'))


# 删除商品
def del_good(request):
    if request.method == 'GET':
        good_id = request.GET.get('good_id')
        good = GoodsModel.objects.filter(pk=good_id)
        if good:
            good.delete()
        return HttpResponseRedirect(reverse('back_web:index'))


# 添加商品
def add_goods(request):
    if request.method == 'GET':
        group_list = GroupModel.objects.all()
        return render(request, 'back_web/add_goods.html', {'group_list': group_list})
    if request.method == 'POST':
        good_name = request.POST.get('name')
        group_id = request.POST.get('group')
        price = request.POST.get('price')
        img = request.FILES.get('img', '')
        intro = request.POST.get('intro')
        format = request.POST.get('format')
        description = request.POST.get('description')
        data = {'group_list': GroupModel.objects.all()}
        if GoodsModel.objects.filter(name=good_name).exists():
            data['msg'] = '商品名称重复'
        else:
            GoodsModel.objects.create(
                name=good_name, group_id=group_id, price=price,
                img=img, description=description, intro=intro, format=format)
            data['msg'] = '添加商品成功'
        return render(request, 'back_web/add_goods.html', data)

back_web/views/group_views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from back_web.models import GroupModel


# 删除分组
def del_group(request):
    if request.method == 'GET':
        group_id = request.GET.get('group_id')
        group = GroupModel.objects.filter(pk=group_id)
        if group:
            group.delete()
        return HttpResponseRedirect(reverse('back_web:show_group'))


# 显示分组信息
def show_group(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        groups = GroupModel.objects.all()
        paginator = Paginator(groups, 5)
        group_list = paginator.page(page)
        data = {
            'group_list': group_list,
            'page': page,
            'num': len(groups)
        }
        return render(request, 'back_web/show_group.html', data)


# 编辑分组
def edit_group(request):
    if request.method == 'GET':
        group_id = request.GET.get('group_id')
        group = GroupModel.objects.filter(pk=group_id).first()
        if group:
            return render(request,
                          'back_web/add_group.html',
                          {'msg': '不改可不填', 'group': group})
    if request.method == 'POST':
        group_id = request.GET.get('group_id')
        group = GroupModel.objects.filter(pk=group_id).first()
        if group:
            name, img = request.POST.get('group_name'), request.FILES.get('group_img', '')
            group.edit(name=name, img=img)
            group.save()
            return HttpResponseRedirect(reverse('back_web:show_group'))


# 添加分组
def add_group(request):
    if request.method == 'GET':
        return render(request, 'back_web/add_group.html')
    if request.method == 'POST':
        group_name = request.POST.get('group_name')
        group_img = request.FILES.get('group_img', '')
        if GroupModel.objects.filter(name=group_name).exists():
            msg = {'code': 302, 'msg': '分组已存在'}
            return render(request, 'back_web/add_group.html', msg)
        GroupModel.objects.create(name=group_name, img=group_img)
        msg = {'code': 200, 'msg': '分组添加成功'}
        return render(request, 'back_web/add_group.html', msg)
    else:
        return render(request, None)

back_web/views/order_views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from back_web.models import OrderModel, DistribModel


def show_order(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        order_status = request.GET.get('order_status', 'all')
        if order_status == 'all':
            orders = OrderModel.objects.all()
        else:
            orders = OrderModel.objects.filter(o_status=order_status)
        paginator = Paginator(orders, 5)
        order_list = paginator.page(page)
        data = {
            'order_list': order_list,
            'page': page,
            'order_status': order_status,
            'num': len(order_list),
            'status_list': ['all', '0', '1', '2', '3', '4']
        }
        return render(request, 'back_web/show_order.html', data)


def edit_order(request):
    if request.method == 'GET':
        order_id = request.GET.get('order_id')
        orders = OrderModel.objects.filter(pk=order_id).first()
        distribs = DistribModel.objects.all()
        if orders:
            data = {
                'orders': orders,
                'distribs': distribs
            }
            return render(request, 'back_web/edit_order.html', data)

    if request.method == 'POST':
        order_id = request.GET.get('order_id')
        distrib_id = request.POST.get('distrib_id')
        order = OrderModel.objects.filter(pk=order_id).first()
        if order:
            order.o_status = 2
            order.distrib_id =distrib_id
            order.save()
            msg = {'msg': '修改成功'}
        else:
            msg = {'msg': '订单不存在'}
        return render(request, 'back_web/edit_order.html', msg)

templates/back_web/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8"/>
<title>后台管理系统</title>
<meta name="author" content="DeathGhost" />
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'back_web/css/style.css' %}">
    {% endblock %}
    {% block js %}
        <!--[if lt IE 9]>
        <script src="js/html5.js"></script>
        <![endif]-->
        <script src="{% static 'back_web/js/jquery.js' %}"></script>
        <script src="{% static 'back_web/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    {% endblock %}
</head>
<body>
    <header>
        <h1><img src="{% static 'back_web/images/admin_logo.png' %}"/></h1>
        <ul class="rt_nav">
        <li><a href="#" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="admin_icon">欢迎登陆：{{ user }}</a></li>
        <li><a href="{% url 'back_web:logout' %}" class="quit_icon">安全退出</a></li>
        </ul>
        </header>
        <!--aside nav-->
    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="{% url 'back_web:index' %}">首页</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>商品信息管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="{% url 'back_web:index' %}">商品列表</a></dd>
                    <!--<dd><a href="{% url 'back_web:add_goods' %}">商品添加</a></dd>-->
                    <dd><a href="{% url 'back_web:show_group' %}">分组管理</a></dd>
                    <!--<dd><a href="{% url 'back_web:add_group' %}">分组添加</a></dd>-->
                    <dd><a href="{% url 'back_web:show_static' %}">静态文件管理</a></dd>
                    <dd><a href="{% url 'back_web:show_banner' %}">轮播文件管理</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单信息</dt>
                    <dd><a href="{% url 'back_web:show_order' %}">订单列表管理</a></dd>
                    <dd><a href="{% url 'back_web:show_freight' %}">运费管理</a></dd>
               </dl>
            </li>
            <li>
                <dl>
                    <dt>配送设置</dt>
                    <dd><a href="{% url 'back_web:show_distrib' %}">配送方式</a></dd>
                    <!--<dd><a href="../notuse/pay_list.html">支付方式</a></dd>-->
                </dl>
            </li>
            <li>
                <dl>
                    <dt>在线统计</dt>
                    <dd><a href="javascript:void(0);">流量统计</a></dd>
                    <!--<dd><a href="sales_volume.html">销售额统计</a></dd>-->
                </dl>
            </li>
            <li>
                <p class="btm_infor">© LiXiaoKai.cn 版权所有</p>
            </li>
        </ul>
    </aside>
    {% block content %}

    {% endblock %}

</body>
</html>

templates/back_web/edit_order.html
{% extends 'back_web/base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <style>
        .dataStatistic{width:400px;height:200px;border:1px solid #ccc;
            margin:0 auto;margin:10px;overflow:hidden}
        #cylindrical{width:400px;height:200px;margin-top:-15px}
        #line{width:400px;height:200px;margin-top:-15px}
        #pie{width:400px;height:200px;margin-top:-15px}
</style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
	(function($){
		$(window).load(function(){
            $($('.lt_aside_nav ul a')[4]).attr('class', 'active');
			$("a[rel='load-content']").click(function(e){
				e.preventDefault();
				var url=$(this).attr("href");
				$.get(url,function(data){
					$(".content .mCSB_container").append(data); //load new content inside .mCSB_container
					//scroll-to appended content
					$(".content").mCustomScrollbar("scrollTo","h2:last");
				});
			});

			$(".content").delegate("a[href='top']","click",function(e){
				e.preventDefault();
				$(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
			});

		});
	})(jQuery);
</script>
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">订单管理</h2>
       <a class="fr top_rt_btn" href="{% url 'back_web:show_order' %}">返回订单列表</a>
      </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <section>
          <ul class="ulColumn2">
           <li>
            <span class="item_name" style="width:120px;">订单编号：</span>
            <input type="text" class="textbox textbox_295" value="{{ orders.o_num }}"
                   placeholder="订单编号..."
                   name="o_num"/>
            <span class="errorTips">{{ msg }}</span>
           </li>
           <li>
            <span class="item_name" style="width:120px;">配送方式：</span>
               <select name="distrib_id" id="">
                   {% for distrib in distribs %}
                   <option value="{{ distrib.id }}">{{ distrib.name }}</option>
                   {% endfor %}
               </select>
           </li>
           <li>
            <span class="item_name" style="width:120px;"></span>
            <input type="submit" class="link_btn"/>
           </li>
          </ul>
         </section>
        </form>
 </div>
</section>
{% endblock %}

templates/back_web/index.html
{% extends 'back_web/base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <style>
        .dataStatistic{width:400px;height:200px;border:1px solid #ccc;
            margin:0 auto;margin:10px;overflow:hidden}
        #cylindrical{width:400px;height:200px;margin-top:-15px}
        #line{width:400px;height:200px;margin-top:-15px}
        #pie{width:400px;height:200px;margin-top:-15px}
</style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
	(function($){
		$(window).load(function(){
            $($('.lt_aside_nav ul a')[0]).attr('class', 'active');
			$("a[rel='load-content']").click(function(e){
				e.preventDefault();
				var url=$(this).attr("href");
				$.get(url,function(data){
					$(".content .mCSB_container").append(data); //load new content inside .mCSB_container
					//scroll-to appended content
					$(".content").mCustomScrollbar("scrollTo","h2:last");
				});
			});

			$(".content").delegate("a[href='top']","click",function(e){
				e.preventDefault();
				$(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
			});

		});
	})(jQuery);
</script>
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">商品列表</h2>
       <a href="{% url 'back_web:add_goods' %}" class="fr top_rt_btn add_icon">添加商品</a>
      </div>
      <section class="mtb">
       <select class="select">
        <option>下拉菜单</option>
       </select>
       <input type="text" class="textbox textbox_225" placeholder="输入产品关键词或产品货号..."/>
       <input type="button" value="查询" class="group_btn"/>
      </section>
      <table class="table">
       <tr>
           <th>序号</th>
        <th>缩略图</th>
        <th>产品名称</th>
        <th>单价</th>
           <th>规格</th>
           <th>简介</th>
        <th>类型</th>
        <th>操作</th>
       </tr>
          <!-- 处理显示商品信息 -->
          {% for good in good_list %}
       <tr>
       <td class="center">{{ forloop.counter }}</td>
        <td class="center"><img src="/media/{{ good.img }}" width="50" height="50"/></td>
        <td class="center">{{ good.name }}</td>
        <td class="center"><strong class="rmb_icon">{{ good.price }}</strong></td>
           <td class="center"><strong class="val_icon">{{ good.format }}</strong></td>
           <td class="center"><strong class="val_icon">{{ good.intro }}</strong></td>
           <td class="center">{{ good.group.name }}</td>
        <td class="center">
         <a href="{% url 'back_web:edit_good' %}?good_id={{ good.id }}" title="编辑" class="link_icon">&#101;</a>
         <a href="{% url 'back_web:del_good' %}?good_id={{ good.id }}" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
          {% endfor %}
          <!-- 处理结束 -->
      </table>
      <aside class="paging">
          <!-- 处理页码 -->
       <a href="{% url 'back_web:index' %}">首页</a>
          {% if good_list.has_previous %}
              <a href="{% url 'back_web:index' %}?page={{ good_list.previous_page_number }}">上一页</a>
          {% endif %}
            {% for tmp in good_list.paginator.page_range %}
                {% ifequal tmp page %}
            <a href="{% url 'back_web:index' %}?page={{ tmp }}"
                style="color: red;background-color: white">{{ tmp }}</a>
                {% else %}
            <a href="{% url 'back_web:index' %}?page={{ tmp }}"
                >{{ tmp }}</a>
                {% endifequal %}
          {% endfor %}
        {% if good_list.has_next %}
              <a href="{% url 'back_web:index' %}?page={{ good_list.next_page_number }}">下一页</a>
          {% endif %}
       <a href="{% url 'back_web:index' %}?page={{ good_list.paginator.num_pages }}">尾页</a>
      </aside>
 </div>
</section>
{% endblock %}

templates/back_web/show_banner.html
{% extends 'back_web/base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <style>
        .dataStatistic{width:400px;height:200px;border:1px solid #ccc;
            margin:0 auto;margin:10px;overflow:hidden}
        #cylindrical{width:400px;height:200px;margin-top:-15px}
        #line{width:400px;height:200px;margin-top:-15px}
        #pie{width:400px;height:200px;margin-top:-15px}
</style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
	(function($){
		$(window).load(function(){
            $($('.lt_aside_nav ul a')[3]).attr('class', 'active');
			$("a[rel='load-content']").click(function(e){
				e.preventDefault();
				var url=$(this).attr("href");
				$.get(url,function(data){
					$(".content .mCSB_container").append(data); //load new content inside .mCSB_container
					//scroll-to appended content
					$(".content").mCustomScrollbar("scrollTo","h2:last");
				});
			});

			$(".content").delegate("a[href='top']","click",function(e){
				e.preventDefault();
				$(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
			});

		});
	})(jQuery);
</script>
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">轮播文件列表</h2>
       <a href="{% url 'back_web:add_banner' %}" class="fr top_rt_btn add_icon">添加轮播文件</a>
      </div>
      <section class="mtb">
       <select class="select">
        <option>下拉菜单</option>
       </select>
       <input type="text" class="textbox textbox_225" placeholder="输入产品关键词或产品货号..."/>
       <input type="button" value="查询" class="group_btn"/>
      </section>
      <table class="table">
       <tr>
           <th>序号</th>
        <th>缩略图</th>
        <th>轮播文件名</th>
           <th>操作</th>
       </tr>
          <!-- 处理分组信息 -->
          {% for banner in banner_list %}
       <tr>
       <td class="center">{{ forloop.counter }}</td>
        <td class="center"><img src="/media/{{ banner.img }}" width="50" height="50"/></td>
        <td class="center">{{ banner.name }}</td>
        <td class="center">
         <a href="{% url 'back_web:edit_banner' %}?banner_id={{ banner.id }}" title="编辑" class="link_icon">&#101;</a>
         <a href="{% url 'back_web:del_banner' %}?banner_id={{ banner.id }}" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
          {% endfor %}
          <!-- 处理结束 -->
      </table>
      <aside class="paging">
          <!-- 处理页面 -->
          <a href="{% url 'back_web:show_banner' %}">首页</a>
          {% if banner_list.has_previous %}
              <a href="{% url 'back_web:show_banner' %}?page={{ banner_list.previous_page_number }}">上一页</a>
          {% endif %}
          {% for tmp in banner_list.paginator.page_range %}
              {% ifequal tmp page %}
                <a href="{% url 'back_web:show_banner' %}?page={{ tmp }}"
                    style="color: red;background-color: white">{{ tmp }}</a>
                  {% else %}
                  <a href="{% url 'back_web:show_banner' %}?page={{ tmp }}"
                    >{{ tmp }}</a>
              {% endifequal %}
          {% endfor %}
          {% if banner_list.has_next %}
              <a href="{% url 'back_web:show_banner' %}?page={{ banner_list.next_page_number }}">下一页</a>
          {% endif %}
       <a href="{% url 'back_web:show_banner' %}?page={{ banner_list.paginator.num_pages }}">尾页</a>
      </aside>
 </div>
</section>
{% endblock %}