fruits_family/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fruits_family import settings
from fruits_shop.views import FruitShopView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^back_web/', include('back_web.urls', namespace='back_web')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^fruits_shop/', include('fruits_shop.urls', namespace='fruits_shop')),
    url(r'^$', FruitShopView.as_view()),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fruits_shop/urls.py
from django.conf.urls import url

from fruits_shop import views

urlpatterns = [
    url(r'^index/', views.FruitShopView.as_view(), name='index'),
    url(r'^detail/', views.fruit_detail, name='detail'),
    url(r'^change_num/', views.change_num, name='change_num'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^get_cart_count/', views.get_cart_count, name='get_cart_count'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^subtotal/', views.subtotal, name='subtotal'),
    url(r'^total_price/', views.total_price, name='total_price'),
    url(r'^cart_delete/', views.cart_delete, name='cart_delete'),
    url(r'^change_status/', views.change_status, name='change_status'),
    url(r'^make_order/', views.make_order, name='make_order'),
    url(r'^order_pay/', views.order_pay, name='order_pay'),

]

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^show_address/', views.show_address, name='show_address'),
    url(r'^add_address/', views.add_address, name='add_address'),
    url(r'^edit_address/', views.edit_address, name='edit_address'),
    url(r'^del_address/', views.del_address, name='del_address'),
    url(r'^user_order_info/',views.user_order_info, name='user_order_info'),


]

fruits_shop/views.py
import json

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView

from back_web.models import BannerModel, StaticModel, GroupModel,\
    GoodsModel, CartModel

from utils.functions import random_list


class FruitShopView(ListView):
    """商店商品显示视图类"""
    template_name = 'fruits_shop/index.html'
    context_object_name = 'groups'
    model = GroupModel

    def get_context_data(self, **kwargs):
        kwargs['banners'] = BannerModel.objects.all()
        kwargs['statics'] = StaticModel.objects.all()
        kwargs['logo'] = StaticModel.objects.filter(name='LOGO').first()
        return super(FruitShopView, self).get_context_data(**kwargs)


# 商品详情页面
def fruit_detail(request):
    if request.method == 'GET':
        good_id = request.GET.get('good_id')
        good = GoodsModel.objects.filter(pk=good_id).first()
        logo = StaticModel.objects.filter(name='LOGO').first()
        groups = GroupModel.objects.all()
        goods_list = GoodsModel.objects.filter(~Q(pk=good_id))
        others = random_list(goods_list)
        data = {
            'good': good,
            'logo': logo,
            'groups': groups,
            'others': others,
        }
        return render(request, 'fruits_shop/detail.html', data)


# 改变个数api
def change_num(request):
    if request.method == 'GET':
        change_type = request.GET.get('change_type')
        value = int(request.GET.get('value'))
        good_id = request.GET.get('good_id')
        if change_type == '1':
            value += 1
        elif change_type == '0':
            if value > 1:
                value -= 1
        good = GoodsModel.objects.filter(pk=good_id).first()
        total = value * float(good.price)
        total = '%.2f' % total

        user = request.user
        if user.id:
            cart = CartModel.objects.filter(good_id=good_id, user=user).first()
            if cart:
                cart.count = value
                cart.save()
                return JsonResponse({'code': 200, 'value': value, 'total': total})

        return JsonResponse({'code': 200, 'value': value, 'total': total})


# 添加至购物车
def add_cart(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            num = int(request.GET.get('num'))
            good_id = request.GET.get('good_id')
            cart = CartModel.objects.filter(good_id=good_id, user=user).first()
            if cart:
                cart.count += num
                cart.save()
            else:
                CartModel.objects.create(good_id=good_id, user=user, count=num)
            return JsonResponse({'code': 200})
        return JsonResponse({'code': 302})


# 购物车显示接口
def get_cart_count(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            cart_list = CartModel.objects.filter(user=user)
            count = 0
            for cart in cart_list:
                count += cart.count
            return JsonResponse({'code': 200, 'count': count})
        return JsonResponse({'code': 302})


# 显示购物车页面数据
def cart(request):
    if request.method == 'GET':
        user = request.user
        logo = StaticModel.objects.filter(name='LOGO').first()
        data = {'logo': logo}
        if user.id:
            cart_list = CartModel.objects.filter(user=user)
            all_select = True
            for cart in cart_list:
                if not cart.is_select:
                    all_select =False
                    break
            data['cart_list'] = cart_list
            data['all_select'] = all_select
        else:
            data['msg'] = '请登录后查看购物车'
        return render(request, 'fruits_shop/cart.html', data)


# 购物车小计接口
def subtotal(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            cart_list = CartModel.objects.filter(user=user)
            total_list = []
            for cart in cart_list:
                tmp = {}
                tmp['cart_id'] = cart.id
                total = float(cart.good.price) * cart.count
                tmp['total'] = '%.2f' % total
                total_list.append(tmp)
            data = {'code': 200, 'total_list': total_list}
        else:
            data = {'code': 302}
        return JsonResponse(data)


# 总价计价接口
def total_price(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            cart_list = CartModel.objects.filter(user=user, is_select=True)
            total, count, all_count = 0, 0, 0
            for cart in CartModel.objects.filter(user=user):
                all_count += cart.count
            for cart in cart_list:
                total += float(cart.good.price) * cart.count
                count += cart.count
            total = '%.2f' % total
            data = {'code': 200, 'total': total, 'count': count, 'all_count': all_count}
        else:
            data = {'code': 302}
        return JsonResponse(data)


# 购物车订单删除
def cart_delete(request):
    if request.method == 'GET':
        user = request.user
        cart_id = request.GET.get('cart_id')
        if user.id:
            cart_info = CartModel.objects.filter(id=cart_id, user=user)
            if cart_info:
                cart_info.delete()
                data = {'code': 200}
            else:
                data = {'code': 302}
        else:
            data = {'code': 302}
        return JsonResponse(data)


# 勾选--全选
def change_status(request):
    if request.method == 'POST':
        user = request.user
        if user.id:
            all_change_status = True if request.POST.get('all_change_status') == 'true' \
                else False
            if all_change_status:
                all_value = True if request.POST.get('all_value') == 'true' else False
                cart_list = CartModel.objects.filter(user=user)
                for cart in cart_list:
                    cart.is_select = all_value
                    cart.save()
                data = {'code': 200}
            else:
                cart_id = request.POST.get('cart_id')
                status = True if request.POST.get('change_status') == 'true' else False
                CartModel.objects.filter(user=user, id=cart_id).update(is_select=status)
                data = {'code': 200}
        else:
            data = {'code': 302}
        return JsonResponse(data)

fruits_shop/views/cart_views.py
from django.http import JsonResponse
from django.shortcuts import render

from back_web.models import StaticModel, GoodsModel, CartModel


# 改变个数api
def change_num(request):
    if request.method == 'GET':
        change_type = request.GET.get('change_type')
        value = int(request.GET.get('value'))
        good_id = request.GET.get('good_id')
        if change_type == '1':
            value += 1
        elif change_type == '0':
            if value > 1:
                value -= 1
        good = GoodsModel.objects.filter(pk=good_id).first()
        total = value * float(good.price)
        total = '%.2f' % total

        user = request.user
        if user.id:
            cart = CartModel.objects.filter(good_id=good_id, user=user).first()
            if cart:
                cart.count = value
                cart.save()
                return JsonResponse({'code': 200, 'value': value, 'total': total})

        return JsonResponse({'code': 200, 'value': value, 'total': total})


# 添加至购物车
def add_cart(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            num = int(request.GET.get('num'))
            good_id = request.GET.get('good_id')
            cart = CartModel.objects.filter(good_id=good_id, user=user).first()
            if cart:
                cart.count += num
                cart.save()
            else:
                CartModel.objects.create(good_id=good_id, user=user, count=num)
            return JsonResponse({'code': 200})
        return JsonResponse({'code': 302})


# 购物车显示接口
def get_cart_count(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            cart_list = CartModel.objects.filter(user=user)
            count = 0
            for cart in cart_list:
                count += cart.count
            return JsonResponse({'code': 200, 'count': count})
        return JsonResponse({'code': 302})


# 显示购物车页面数据
def cart(request):
    if request.method == 'GET':
        user = request.user
        logo = StaticModel.objects.filter(name='LOGO').first()
        data = {'logo': logo}
        if user.id:
            cart_list = CartModel.objects.filter(user=user)
            all_select = True
            for cart in cart_list:
                if not cart.is_select:
                    all_select =False
                    break
            data['cart_list'] = cart_list
            data['all_select'] = all_select
        else:
            data['msg'] = '请登录后查看购物车'
        return render(request, 'fruits_shop/cart.html', data)


# 购物车小计接口
def subtotal(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            cart_list = CartModel.objects.filter(user=user)
            total_list = []
            for cart in cart_list:
                tmp = {}
                tmp['cart_id'] = cart.id
                total = float(cart.good.price) * cart.count
                tmp['total'] = '%.2f' % total
                total_list.append(tmp)
            data = {'code': 200, 'total_list': total_list}
        else:
            data = {'code': 302}
        return JsonResponse(data)


# 总价计价接口
def total_price(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            cart_list = CartModel.objects.filter(user=user, is_select=True)
            total, count, all_count = 0, 0, 0
            for cart in CartModel.objects.filter(user=user):
                all_count += cart.count
            for cart in cart_list:
                total += float(cart.good.price) * cart.count
                count += cart.count
            total = '%.2f' % total
            data = {'code': 200, 'total': total, 'count': count, 'all_count': all_count}
        else:
            data = {'code': 302}
        return JsonResponse(data)


# 购物车订单删除
def cart_delete(request):
    if request.method == 'GET':
        user = request.user
        cart_id = request.GET.get('cart_id')
        if user.id:
            cart_info = CartModel.objects.filter(id=cart_id, user=user)
            if cart_info:
                cart_info.delete()
                data = {'code': 200}
            else:
                data = {'code': 302}
        else:
            data = {'code': 302}
        return JsonResponse(data)


# 勾选--全选
def change_status(request):
    if request.method == 'POST':
        user = request.user
        if user.id:
            all_change_status = True if request.POST.get('all_change_status') == 'true' \
                else False
            if all_change_status:
                all_value = True if request.POST.get('all_value') == 'true' else False
                cart_list = CartModel.objects.filter(user=user)
                for cart in cart_list:
                    cart.is_select = all_value
                    cart.save()
                data = {'code': 200}
            else:
                cart_id = request.POST.get('cart_id')
                status = True if request.POST.get('change_status') == 'true' else False
                CartModel.objects.filter(user=user, id=cart_id).update(is_select=status)
                data = {'code': 200}
        else:
            data = {'code': 302}
        return JsonResponse(data)

fruits_shop/views/good_views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView

from back_web.models import BannerModel, StaticModel, GroupModel,\
    GoodsModel
from utils.functions import random_list


class FruitShopView(ListView):
    """商店商品显示视图类"""
    template_name = 'fruits_shop/index.html'
    context_object_name = 'groups'
    model = GroupModel

    def get_context_data(self, **kwargs):
        kwargs['banners'] = BannerModel.objects.all()
        kwargs['statics'] = StaticModel.objects.all()
        kwargs['logo'] = StaticModel.objects.filter(name='LOGO').first()
        return super(FruitShopView, self).get_context_data(**kwargs)


# 商品详情页面
def fruit_detail(request):
    if request.method == 'GET':
        good_id = request.GET.get('good_id')
        good = GoodsModel.objects.filter(pk=good_id).first()
        logo = StaticModel.objects.filter(name='LOGO').first()
        groups = GroupModel.objects.all()
        goods_list = GoodsModel.objects.filter(~Q(pk=good_id))
        others = random_list(goods_list)
        data = {
            'good': good,
            'logo': logo,
            'groups': groups,
            'others': others,
        }
        return render(request, 'fruits_shop/detail.html', data)

fruits_shop/views/order_views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from back_web.models import CartModel, OrderModel, OrderGoodsModel, AddressModel, StaticModel
from utils.functions import order_num


# 显示订单生成页面
def make_order(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            carts = CartModel.objects.filter(user=user, is_select=True)
            logo = StaticModel.objects.filter(name='LOGO').first()
            address = AddressModel.objects.filter(user=user).first()
            cost = float(address.area.cost) if address else 0
            if carts:
                total = 0
                for info in carts:
                    total += float(info.good.price) * info.count
                data = {'cost': cost, 'total_price': total,
                        'address': address, 'logo': logo, 'carts': carts}
                return render(request, 'fruits_shop/place_order.html', data)

    if request.method == 'POST':
        user = request.user
        if user.id:
            carts = CartModel.objects.filter(user=user, is_select=True)
            if carts:
                address_id = request.POST.get('address_id')
                address_obj = AddressModel.objects.filter(pk=address_id).first()
                cost = float(address_obj.area.cost)
                address = address_obj.area.area + address_obj.address
                o_num = order_num()
                order = OrderModel.objects.create(user=user, o_num=o_num, address=address,
                                                  cost=cost, name=address_obj.name,
                                                  tel_phone=address_obj.tel_phone)
                total = 0
                for info in carts:
                    total += float(info.good.price) * info.count
                    OrderGoodsModel.objects.create(order=order, goods=info.good,
                                                   goods_num=info.count)
                carts.delete()
                order.total_price = '%.2f' % (total + cost)
                order.save()
                return HttpResponseRedirect(reverse('fruits_shop:order_pay') + '?order_id=' + str(order.id))


# 确认支付
def order_pay(request):
    if request.method == 'GET':
        order_id = request.GET.get('order_id')
        return render(request, 'fruits_shop/order_pay.html', {'order_id': order_id})

    if request.method == 'POST':
        user = request.user
        if user.id:
            order_id = request.POST.get('order_id')
            order = OrderModel.objects.filter(pk=order_id).first()
            order.o_status = 1
            order.save()
            return JsonResponse({'code': 200})

templates/fruits_shop/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
{% load lk_filter %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}
        天天生鲜-首页
        {% endblock %}
    </title>
    {% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'fruits_shop/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fruits_shop/css/main.css' %}">
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">

                    {% if not user.username %}
					    <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
					    <a href="{% url 'user:register' %}">注册</a>
                        {% else %}
                        {{ user.username }}
                    {% endif %}

				</div>
				<div class="user_link fl">
                    <span>|</span>
					<a href="{% url 'fruits_shop:index' %}">首页</a>
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'fruits_shop:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:user_order_info' %}">我的订单</a>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">注销</a>
				</div>
			</div>
		</div>
	</div>

	{% block content %}

    {% endblock %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 LiXiaoKai All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block js %}
        <script type="text/javascript" src="{% static 'fruits_shop/js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'fruits_shop/js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'fruits_shop/js/slide.js' %}"></script>
        <script type="text/javascript" src="{% static 'fruits_shop/js/cart.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/fruits_shop/cart.html
{% extends 'fruits_shop/base.html' %}
{% load static %}
{% block title %}
	天天生鲜-购物车
{% endblock %}
{% block css %}
    {{ block.super }}
{% endblock %}

{% block content %}
	<div class="search_bar clearfix">
		<a href="{% url 'fruits_shop:index' %}" class="logo fl"><img src="/media/{{ logo.img }}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
        <div class="guest_cart fr">
			<a href="{% url 'fruits_shop:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
    <div style="color: red;text-align: center">{{ msg }}</div>
	<div class="total_count">全部商品<em></em>件</div>
    {% csrf_token %}
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for cart in cart_list %}
	<ul class="cart_list_td clearfix">
        {% if cart.is_select %}
		<li class="col01"><input type="checkbox" name="{{ cart.id }}" checked></li>
        {% else %}
        <li class="col01"><input type="checkbox" name="{{ cart.id }}"></li>
        {% endif %}
		<li class="col02"><img src="/media/{{ cart.good.img }}"></li>
		<li class="col03">{{ cart.good.name }}<br><em>{{ cart.good.price }}元/{{ cart.good.format }}</em></li>
		<li class="col04">{{ cart.good.format }}</li>
		<li class="col05">{{ cart.good.price }}元</li>
		<li class="col06">
			<div class="num_add" name="{{ cart.good.id }}">
				<a href="javascript:void(0);" class="add fl change">+</a>
				<input type="text" class="num_show fl" value="{{ cart.count }}">
				<a href="javascript:void(0);" class="minus fl change">-</a>
			</div>
		</li>
		<li class="col07 subtotal" id="{{ cart.id }}" ></li>
		<li class="col08"><a href="javascript:void(0);" onclick="cart_delete({{ cart.id }})">删除</a></li>
	</ul>
    {% endfor %}
	<ul class="settlements">
		<li class="col01">
            {% if all_select %}
            <input type="checkbox" name="" checked="">
            {% else %}
            <input type="checkbox" name="">
            {% endif %}
        </li>
		<li class="col02">全选</li>
		<li class="col03" id="total">合计(不含运费)：<span>¥</span><em>0</em><br>共计<b>0</b>件商品</li>
		<li class="col04"><a href="{% url 'fruits_shop:make_order' %}">去结算</a></li>
	</ul>
{% endblock %}
{% block js %}
	<script type="text/javascript" src="{% static 'fruits_shop/js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'fruits_shop/js/cart.js' %}"></script>
    <script type="text/javascript">
    $(function () {
    Subtotal();
    total_price();
    // 加减点击事件
    $('.change').click(function (e) {
        e.preventDefault();
        var evt = $(e.target);
        var good_id = evt.parent().attr('name');
        var value = evt.parent().find('input').val();
        if (evt.text() == '+'){
            var change_type = 1
        }else if (evt.text() == '-'){
            var change_type = 0
        }
        var data = {'good_id': good_id, 'value': value, 'change_type': change_type};
        $.get('/fruits_shop/change_num/', data, function (data) {
            if (data.code == 200){
                evt.parent().parent().nextAll('.subtotal').text(data.total + '元');
                evt.parent().find('input').val(data.value);
                total_price();
                }
        })
    });
    // 勾选按钮点击事件
    $('.cart_list_td>.col01>input').click(function (evt) {
        var check_status = $(evt.target).prop('checked');
        var cart_id = $(evt.target).attr('name');
        change_status(cart_id, check_status, '', false);
    })
    // 全选按钮点击事件
    $('.settlements>.col01>input').click(function (evt) {
        var all_value = $(evt.target).prop('checked');
        var all_change_status = true;
        change_status('', '', all_value, all_change_status)
    })
});
    </script>
{% endblock %}

templates/fruits_shop/detail.html
{% extends 'fruits_shop/base.html' %}
{% load static %}
{% block title %}
    天天生鲜-商品详情
{% endblock %}
{% block css %}
    {{ block.super }}
{% endblock %}

{% block content %}
	<div class="search_bar clearfix">
		<a href="{% url 'fruits_shop:index' %}" class="logo fl"><img src="/media/{{ logo.img }}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'fruits_shop:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for group in groups %}
					<li><a href="{% url 'fruits_shop:index' %}#{{ group.icon_type }}" class="{{ group.icon_type }}">{{ group.name }}</a></li>
                    {% endfor %}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'fruits_shop:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ good.group.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/media/{{ good.img }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good.name }}</h3>
			<p>{{ good.intro }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good.price }}</em></span>
				<span class="show_unit">单  位：{{ good.format }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1" id="{{ good.id }}" name="num">
					<a href="javascript:void(0);" class="add fr change">+</a>
					<a href="javascript:void(0);" class="minus fr change">-</a>
				</div> 
			</div>
			<div class="total">总价：<em>{{ good.price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:void(0);" class="buy_btn">立即购买</a>
				<a href="javascript:void(0);" class="add_cart" id="add_cart" >加入购物车</a>
			</div>
                <div class="add_jump"></div>
		</div>
	</div>
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for other in others %}
					<li>
						<a href="{% url 'fruits_shop:detail' %}?good_id={{ other.id }}"><img src="/media/{{ other.img }}"></a>
						<h4><a href="{% url 'fruits_shop:detail' %}?good_id={{ other.id }}">{{ other.name }}</a></h4>
						<div class="prize">￥{{ other.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
				</dl>
                <div id="content">
                    {% autoescape off %}
                        {{ good.description }}
                    {% endautoescape %}
                </div>
			</div>

		</div>
	</div>


{% endblock %}
{% block js %}

	<script type="text/javascript" src="{% static 'fruits_shop/js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'fruits_shop/js/cart.js' %}"></script>
	<script type="text/javascript">
        $(function () {
            // 滑动 -- 添加购物车
            $('#add_cart').click(function(){
                var num = $('input[name="num"]').val();
                var good_id = $('input[name="num"]').attr('id');
                var data = {'num': num, 'good_id': good_id};
                $.get('/fruits_shop/add_cart/', data, function (json) {
                    if (json.code == 200){
                        // 定义一个把函数作为参数的函数 内部返送ajax请求，
                        // 吧ajax的相应值作为参数传给参数函数用于处理
                        var $add_x = $('#add_cart').offset().top;
                        var $add_y = $('#add_cart').offset().left;
                        var $to_x = $('#show_count').offset().top;
                        var $to_y = $('#show_count').offset().left;
                        $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
                        get_cart_count(function (data) {
                            $(".add_jump").stop().animate({
				            'left': $to_y+7,
				            'top': $to_x+7},
				            "fast", function() {
					        $(".add_jump").fadeOut('fast',function(){
						        $('#show_count').html(data.count);
					        });
			            });
                        });

                    }
                })
            });
            // 改变个数和计价
            $('.change').on('click', function(evt){
                var $evt = $(evt.target);
                var $input = $evt.parent().children('input');
                var value = $input.val();
                var good_id = $input.attr('id');
                if ($evt.text() == '+'){
                    var change_type = 1;
                }else if ($evt.text() == '-'){
                    var change_type = 0;
                }
                var data = {'change_type': change_type,
                    'value': value, 'good_id': good_id};
                $.get('/fruits_shop/change_num/', data, function (data) {
                    if (data.code == 200){
                        $('.num_show').val(data.value);
                        $('.total>em').text(data.total + '元')
                    }
                })
            });
            // 初始化显示购物车
            get_cart_count(show)
        });

	</script>
{% endblock %}