back_web/urls.py
from django.conf.urls import url

from back_web import views

urlpatterns = [
    # 登陆
    url(r'^$', views.login, name='login'),
    url(r'^login/', views.login),
    # 注销
    url(r'^logout/', views.logout, name='logout'),

    # 首页 即商品列表
    url(r'^index/', views.index, name='index'),
    # 添加商品
    url(r'^add_goods/', views.add_goods, name='add_goods'),
    # 编辑商品
    url(r'^edit_good/', views.edit_good, name='edit_good'),
    # 删除商品
    url(r'^del_good/', views.del_good, name='del_good'),

    # 添加分组
    url(r'^add_group/', views.add_group, name='add_group'),
    # 显示分组信息
    url(r'^show_group/', views.show_group, name='show_group'),
    # 删除分组
    url(r'^del_group/',views.del_group, name='del_group'),
    # 编辑分组信息
    url(r'^edit_group/', views.edit_group, name='edit_group'),

    # 添加静态文件
    url(r'^add_static/', views.add_static, name='add_static'),
    # 显示静态文件
    url(r'^show_static/', views.show_static, name='show_static'),
    # 编辑静态文件
    url(r'^edit_static/', views.edit_static, name='edit_static'),
    # 删除静态文件
    url(r'^del_static/',views.del_static, name='del_static'),

    # 添加轮播文件
    url(r'^add_banner/', views.add_banner, name='add_banner'),
    # 显示轮播文件
    url(r'^show_banner/', views.show_banner, name='show_banner'),
    # 编辑轮播文件
    url(r'^edit_banner/', views.edit_banner, name='edit_banner'),
    # 删除轮播文件
    url(r'^del_banner/', views.del_banner, name='del_banner'),

    # 添加运费
    url(r'^add_freight/', views.add_freight, name='add_freight'),
    # 显示运费设置
    url(r'^show_freight/', views.show_freight, name='show_freight'),

    # 后台订单显示
    url(r'^show_order/', views.show_order, name='show_order'),
    # 订单状态修改
    url(r'^edit_order/', views.edit_order, name='edit_order'),

    # 显示配送方式
    url(r'^show_distrib/', views.show_distrib, name='show_distrib'),
    # 添加配送方式
    url(r'^add_distrib/', views.add_distrib, name='add_distrib'),
    # 删除url
    url(r'^del_distrib/', views.del_distrib, name='del_distrib'),

]

fruits_family/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fruits_family import settings
from fruits_shop.views import FruitShopView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^back_web/', include('back_web.urls', namespace='back_web')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^fruits_shop/', include('fruits_shop.urls', namespace='fruits_shop')),
    url(r'^$', FruitShopView.as_view()),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fruits_shop/urls.py
from django.conf.urls import url

from fruits_shop import views

urlpatterns = [
    url(r'^index/', views.FruitShopView.as_view(), name='index'),
    url(r'^detail/', views.fruit_detail, name='detail'),
    url(r'^change_num/', views.change_num, name='change_num'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^get_cart_count/', views.get_cart_count, name='get_cart_count'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^subtotal/', views.subtotal, name='subtotal'),
    url(r'^total_price/', views.total_price, name='total_price'),
    url(r'^cart_delete/', views.cart_delete, name='cart_delete'),
    url(r'^change_status/', views.change_status, name='change_status'),
    url(r'^make_order/', views.make_order, name='make_order'),
    url(r'^order_pay/', views.order_pay, name='order_pay'),

]

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^show_address/', views.show_address, name='show_address'),
    url(r'^add_address/', views.add_address, name='add_address'),
    url(r'^edit_address/', views.edit_address, name='edit_address'),
    url(r'^del_address/', views.del_address, name='del_address'),
    url(r'^user_order_info/',views.user_order_info, name='user_order_info'),


]

back_web/models.py
from django.db import models

from user.models import UserModel


# 商品分组
class GroupModel(models.Model):

    name = models.CharField(max_length=100, unique=True)
    img = models.ImageField(upload_to='group')
    icon_type = models.CharField(max_length=32, null=True)

    class Meta:
        db_table = 'tb_fruit_group'

    def edit(self, name, img):
        self.name = name if (name != self.name and name not in ('', None)) else self.name
        self.img = img if (img != self.img and img not in ('', None)) else self.img


# 商品
class GoodsModel(models.Model):
    name = models.CharField(max_length=100)     # 名称
    img = models.ImageField(upload_to='goods')  # 图片
    group = models.ForeignKey(GroupModel)       # 关联分组外键
    price = models.CharField( max_length=32, default=0.00)  # 单价
    intro = models.CharField(max_length=255, null=True)     # 简述
    format = models.CharField(max_length=32, null=True)     # 规格
    description = models.TextField(null=True)               # 详情

    class Meta:
        db_table = 'tb_fruits_good'

    def edit(self, name, img, group, price, description, intro, format):
        self.name = name if (name != self.name and name not in ('', None)) else self.name
        self.img = img if (img != self.img and img not in ('', None)) else self.img
        self.group = group if (group != self.group_id and group not in ('', None)) \
            else self.group_id
        self.price = price if (price != self.price and price not in ('', None)) else self.price
        self.description = description if \
            (description != self.description and description not in ('', None)) \
            else self.description
        self.intro = intro if (intro != self.intro and intro not in ('', None)) else self.intro
        self.format = format if (format != self.format and format not in ('', None)) \
            else self.format

    def info_dict(self):
        data = {'name': self.name, 'img': self.img}


# 静态图
class StaticModel(models.Model):
    img = models.ImageField(upload_to='static_file')  # 图片
    name = models.CharField(max_length=100)  # 名称

    class Meta:
        db_table = 'tb_static'

    def edit(self, name, img):
        self.name = name if (name != self.name and name not in ('', None)) else self.name
        self.img = img if (img != self.img and img not in ('', None)) else self.img


# 轮播图
class BannerModel(models.Model):
    img = models.ImageField(upload_to='banner')  # 图片
    name = models.CharField(max_length=100)  # 名称

    class Meta:
        db_table = 'tb_banner'

    def edit(self, name, img):
        self.name = name if (name != self.name and name not in ('', None)) else self.name
        self.img = img if (img != self.img and img not in ('', None)) else self.img


# 购物车
class CartModel(models.Model):

    good = models.ForeignKey(GoodsModel)    # 关联商品模型外键
    count = models.IntegerField(default=1)    # 商品个数
    user = models.ForeignKey(UserModel)    # 关联用户模型外键
    is_select = models.BooleanField(default=True)   # 选中状态

    class Meta:
        db_table = 'tb_cart'


# 运费模型
class FreightModel(models.Model):

    area = models.CharField(max_length=40, unique=True)  # 区域
    cost = models.CharField(max_length=10)  # 运费

    class Meta:
        db_table = 'tb_freight'


# 收货地址
class AddressModel(models.Model):

    user = models.ForeignKey(UserModel)     # 关联用户
    area = models.ForeignKey(FreightModel)   # 区域省份
    address = models.CharField(max_length=40, default='')    # 地址
    name = models.CharField(max_length=32, default='')   # 收货人姓名
    tel_phone = models.CharField(max_length=13, default='')  # 收货人电话

    class Meta:
        db_table = 'tb_user_address'

    # 编辑方法
    def edit(self, area_id, address, name, tel_phone):
        self.area_id = area_id if (area_id != self.area_id and area_id not in ('', None)) else self.area_id
        self.address = address if (address != self.address and address not in ('', None)) else self.address
        self.name = name if (name != self.name and name not in ('', None)) else self.name
        self.tel_phone = tel_phone if (tel_phone != self.tel_phone and tel_phone not in ('', None)) \
            else self.tel_phone
        self.save()


# 配送方式
class DistribModel(models.Model):
    name = models.CharField(max_length=255)
    img = models.ImageField(upload_to='distrib')

    class Meta:
        db_table = 'tb_distrib'


# 订单
class OrderModel(models.Model):
    user = models.ForeignKey(UserModel)  # 关联用户
    o_num = models.CharField(max_length=64)  # 订单号
    # 0 代表已下单，但是未付款， 1 已付款未发货  2 已付款，已发货.....
    o_status = models.IntegerField(default=0)  # 状态
    o_create = models.DateTimeField(auto_now_add=True)  # 创建时间
    address = models.CharField(max_length=255, default='')   # 收货地址
    cost = models.FloatField(default=10.0)                  # 运费
    name = models.CharField(max_length=20, default='')                  # 收货人姓名
    tel_phone = models.CharField(max_length=13, default='')  # 收货人电话
    total_price = models.CharField(max_length=10)   # 订单金额
    distrib = models.ForeignKey(DistribModel, null=True)

    class Meta:
        db_table = 'tb_order'


# 订单商品中间表
class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(GoodsModel)  # 关联的商品
    order = models.ForeignKey(OrderModel)  # 关联的订单
    goods_num = models.IntegerField(default=1)  # 商品的个数

    class Meta:
        db_table = 'tb_order_goods'

user/models.py
from django.db import models


class UserModel(models.Model):

    username = models.CharField(max_length=20, unique=True)    # 用户名
    password = models.CharField(max_length=255, db_column='passwd')    # 密码
    email = models.CharField(max_length=64)    # 邮箱
    is_delete = models.BooleanField(default=False)    # 删除状态

    class Meta:
        db_table = 'tb_fruits_user'


class UserTicketModel(models.Model):
    user = models.ForeignKey(UserModel)  # 关联用户
    session_id = models.CharField(max_length=256)   # session_id
    out_time = models.DateTimeField()  # 过期时间

    class Meta:
        db_table = 'tb_fruits_users_ticket'

user/views/auth_views.py
import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.hashers import make_password, check_password
from django.urls import reverse

from user.models import UserModel, UserTicketModel
from utils.functions import random_session


# 注册
def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')

    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        msg = {}
        if UserModel.objects.filter(username=user_name).exists():
            msg['code'], msg['msg'] = 302, '用户名已存在'
        password1 = request.POST.get('pwd')
        password2 = request.POST.get('pwd2')
        if password1 != password2:
            msg['code'], msg['msg'] = 302, '两次密码不一致。'
        password = make_password(password1)
        email = request.POST.get('email')
        UserModel.objects.create(username=user_name,
                                 password=password,
                                 email=email)
        msg['code'], msg['msg'] = 200, '用户注册成功'
        return render(request, 'user/register.html', msg)
    return render(request, None)


# 登陆
def login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        msg = {}
        if not all([username, password]):
            return render(request, 'user/login.html',
                          {'code': 302, 'msg': '输入错误'})
        if UserModel.objects.filter(username=username).exists():
            user = UserModel.objects.filter(username=username).first()
            if check_password(password, user.password) and not user.is_delete:
                session_id = random_session(30)
                res = HttpResponseRedirect(reverse('fruits_shop:index'))
                res.set_cookie('session_id', session_id, max_age=60000)
                out_time = datetime.datetime.now() + datetime.timedelta(hours=1)
                UserTicketModel.objects.create(user=user,
                                               session_id=session_id,
                                               out_time=out_time)
                return res
            else:
                msg['msg'], msg['code'] = 302, '用户名密码错误，请重新登陆'
        else:
            msg['msg'], msg['code'] = 302, '用户名密码错误，请重新登陆'
        return render(request, 'user/login.html', msg)


# 注销登陆
def logout(request):
    if request.method == 'GET':
        user = request.user
        session_id = request.COOKIES.get('session_id')
        if user.id:
            session_list = UserTicketModel.objects.filter(user=user, session_id=session_id)
            session_list.delete()
        HttpResponseRedirect(reverse('fruits_shop:index'))

user/views/user_info_views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from back_web.models import AddressModel, StaticModel, FreightModel


# 用户中心显示
def user_center_info(request):
    if request.method == 'GET':
        user = request.user
        logo = StaticModel.objects.filter(name='LOGO').first()
        address_list = AddressModel.objects.filter(user=user)
        data = {'user': user, 'logo': logo, 'address_list': address_list}
        return render(request, 'user/user_center_info.html', data)


# 删除收货地址
def del_address(request):
    if request.method == 'GET':
        addr_id = request.GET.get('addr_id')
        address = AddressModel.objects.filter(id=addr_id).first()
        if address:
            address.delete()
            return HttpResponseRedirect(reverse('user:show_address'))


# 修改收货地址
def edit_address(request):
    if request.method == 'GET':
        addr_id = request.GET.get('addr_id')
        address = AddressModel.objects.filter(id=addr_id).first()
        areas = areas = FreightModel.objects.all()
        if address:
            data = {'address': address, 'areas': areas}
            return render(request, 'user/user_center_add_addr.html', data)
    if request.method == 'POST':
        area, address = request.POST.get('area'), request.POST.get('address')
        tel_phone, name = request.POST.get('tel_phone'), request.POST.get('name')
        addr_id = request.GET.get('addr_id')
        address_obj = AddressModel.objects.filter(id=addr_id).first()
        if address_obj:
            address_obj.edit(area, address, name, tel_phone)
            return HttpResponseRedirect(reverse('user:show_address'))


# 添加收货地址
def add_address(request):
    if request.method == 'GET':
        return render(request, 'user/user_center_add_addr.html')

    if request.method == 'POST':
        area, address = request.POST.get('area'), request.POST.get('address')
        tel_phone, name = request.POST.get('tel_phone'), request.POST.get('name')
        user = request.user
        if not all([area, address, tel_phone, name, user]):
            data = {'msg': '请填写完整信息'}
        elif not user.id:
            data = {'msg': '请登录'}
        else:
            AddressModel.objects.create(area_id=area, address=address,
                                        name=name, tel_phone=tel_phone,
                                        user=user)
            data = {'msg': '添加成功'}
        return render(request, 'user/user_center_add_addr.html', data)


# 显示收货地址
def show_address(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            logo = StaticModel.objects.filter(name='LOGO').first()
            address_list = AddressModel.objects.filter(user=user)
            data = {'user': user, 'logo': logo, 'address_list': address_list}
            return render(request, 'user/user_center_site.html', data)

user/views/user_order_info.py
from django.core.paginator import Paginator
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from back_web.models import OrderModel


# 用户中心订单显示
def user_order_info(request):
    if request.method == 'GET':
        user = request.user
        if user.id:
            page = int(request.GET.get('page', 1))
            orders = OrderModel.objects.filter(user=user).order_by('o_create')
            paginator = Paginator(orders, 5)
            order_list = paginator.page(page)
            data = {
                'order_list': order_list,
                'page': page,
                'num': len(orders),
            }
            return render(request, 'user/user_center_order.html', data)

templates/user/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'fruits_shop/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fruits_shop/css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<a href="#" class="login_logo"><img src="{% static 'fruits_shop/images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    <span>{{ msg }}</span>
					<form action="" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 李晓锴制 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/user/user_center_info.html
{% extends 'fruits_shop/base.html' %}
{% load static %}
{% load lk_filter %}
{% block title %}
天天生鲜-用户中心
{% endblock %}
{% block css %}
{{ block.super }}
    <style>
        #operating {
            display: inline-block;
            font-family: Arial;
            font-size: 16px;
        }
        .title2 {
            display: inline-block;
        }
    </style>
{% endblock %}
{% block content %}
	<div class="search_bar clearfix">
    {% logo as img %}
		<a href="{% url 'fruits_shop:index' %}" class="logo fl"><img src="/media/{{ img }}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="guest_cart fr">
			<a href="{% url 'fruits_shop:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:user_order_info' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:show_address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				    <h3 class="common_title2">基本信息</h3>
                    <ul class="user_info_list">
                        <li><span>用户名：</span>{{ user.username }}</li>
                        <li><span>注册邮箱：</span>{{ user.email }}</li>
                    </ul>
                    <div>
                        <h3 class="common_title2 title2">收货地址</h3>

                    </div>
                    {% if address_list %}

                    {% for address in address_list %}
                    <ul class="user_info_list">
                        <li><span>姓名：</span>{{ address.name}}</li>
                        <li><span>联系方式：</span>{{ address.tel_phone }}</li>
                        <li><span>联系地址：</span>{{ address.area.area }}{{ address.address }}</li>
                    </ul>
                    {% endfor %}
                        {% else %}
                        <p style="color: red; font-size: 16px;text-align: center">您还没有收货地址，
                            点击<a href="{% url 'user:add_address' %}" id="operating">新地址</a>快速添加。</p>
                    {% endif %}
				</div>
		</div>
	</div>
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static 'fruits_shop/js/cart.js' %}"></script>
    <script type="text/javascript">
     get_cart_count(show)
    </script>

{% endblock %}

templates/user/user_center_order.html
{% extends 'fruits_shop/base.html' %}
{% load static %}
{% load lk_filter %}
{% block title %}
    天天生鲜-订单信息
{% endblock %}
{% block css %}
    {{ block.super }}
{% endblock %}
{% block content %}
    {% logo as img %}
	<div class="search_bar clearfix">
		<a href="{% url 'fruits_shop:index' %}" class="logo fl"><img src="/media/{{ img }}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="guest_cart fr">
			<a href="{% url 'fruits_shop:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_order_info' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:show_address' %}">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for order in order_list %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01" style="width: 290px">{{ order.o_create }}</li>
					<li class="col02" style="width: 290px">订单号：{{ order.o_num }}</li>
                    {% if order.o_status == 0 %}
                        <li class="col02 stress">未支付</li>
                    {%  elif order.o_status == 3 %}
                        <li class="col02 stress">已完成</li>
                    {% else %}
                        <li class="col02 stress">已支付</li>
                    {% endif %}

                    <li class="col01" style="width: 290px">收货人：{{ order.name }}</li>
					<li class="col02" style="width: 290px">收货人电话：{{ order.tel_phone }}</li>
					<li class="col02" style="width: 290px">收货地址：{{ order.address }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
                        {% ifequal forloop.counter 1 %}
                        <tr>
                            <th width="60%">商品信息</th>
                            <th width="10%">运费</th>
                            <th width="10%">总价</th>
                            <th width="10%">订单状态</th>
                            <th width="10%">操作</th>
                        </tr>
                        {% endifequal %}
						<tr>

							<td width="60%">
                                {% for ordergood in order.ordergoodsmodel_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/{{ ordergood.goods.img }}"></li>
									<li class="col02">
                                        {{ ordergood.goods.name }}<em>
                                        {{ ordergood.goods.price }}元/
                                        {{ ordergood.goods.format }}</em></li>
									<li class="col03">{{ ordergood.goods_num }}</li>
									<li class="col04">
                                        {{ ordergood.goods.price|sum_tag:ordergood.goods_num|floatformat:2 }}元</li>
								</ul>
                                {% endfor %}
							</td>

							<td width="10%">{{ order.cost|floatformat:2 }}元</td>
                            <td width="10%">{{ order.total_price }}元</td>
                            {% if order.o_status == 0 %}
                                <td width="10%">待付款</td>
							    <td width="10%">
                                    <a href="{% url 'fruits_shop:order_pay' %}?order_id={{ order.id }}"
                                                   class="oper_btn">去付款</a></td>
                                {% elif order.o_status == 3 %}
                                <td width="10%">订单完成</td>
                                <td width="10%"><a href="#">查看签收信息</a></td>
                                {% else  %}
                                <td width="10%">已支付</td>
                                <td width="10%"><a href="#">查看物流信息</a></td>
                            {% endif %}
						</tr>
					</tbody>
				</table>
                {% endfor %}

				<div class="pagenation">
                    <a href="{% url 'user:user_order_info' %}">首页</a>
					{% if order_list.has_previous %}
                        <a href="{% url 'user:user_order_info' %}?page={{ order_list.previous_page_number }}">上一页</a>
                    {% endif %}
                    {% for tmp in order_list.paginator.page_range %}
                        {% ifequal tmp page %}
                            <a href="{% url 'user:user_order_info' %}?page={{ tmp }}"
                               class="active">{{ tmp }}</a>
                        {% else %}
                            <a href="{% url 'user:user_order_info' %}?page={{ tmp }}"
                                >{{ tmp }}</a>
                        {% endifequal %}
                    {% endfor %}
                    {% if order_list.has_next %}
                          <a href="{% url 'user:user_order_info' %}?page={{ order_list.next_page_number }}">下一页</a>
                    {% endif %}
                    <a href="{% url 'user:user_order_info' %}?page={{ order_list.paginator.num_pages }}">尾页</a>
				</div>
		</div>
	</div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'fruits_shop/js/cart.js' %}"></script>
    <script type="text/javascript">
     get_cart_count(show)
    </script>
{% endblock %}

templates/user/user_center_site.html
{% extends 'fruits_shop/base.html' %}
{% block title %}
    天天生鲜-用户中心
{% endblock %}
{% block css %}
    {{ block.super }}
{% endblock %}
{% block content %}

	<div class="search_bar clearfix">
		<a href="{% url 'fruits_shop:index' %}" class="logo fl"><img src="/media/{{ logo.img }}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="guest_cart fr">
			<a href="{% url 'fruits_shop:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_order_info' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:show_address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
            {% for address in address_list %}
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        <span style="display: inline-block;float: right;">
                            <a href="{% url 'user:del_address' %}?addr_id={{ address.id }}">删除</a></span>
                        <span style="display: inline-block;float: right;margin-right: 10px;">
                            <a href="{% url 'user:edit_address' %}?addr_id={{ address.id }}">
                            编辑</a></span>
						<dd>{{ address.area.area }}
                            {{ address.address }}
                            （{{ address.name }} 收）
                            {{ address.tel_phone }}</dd>
					</dl>					
				</div>
            {% endfor %}
                <div>
                    <h3 class="common_title2"><a href="{% url 'user:add_address' %}">添加地址</a></h3>
                </div>
		</div>
	</div>
{% endblock %}